kind: ConfigMap
apiVersion: v1

metadata:
  name: my-properties-file-cm
#immutable: true #ConfigMap can be immutable too
data:
  my.config.db: |
    database="mariadb"
    database_uri="mariadb://localhost:3306"
  each.property.here.is.a.file: | 
    testing=123