kind: ConfigMap
apiVersion: v1

metadata:
  name: my-properties-file-cm

data:
  my.config.db: |
    database="mariadb"
    database_uri="mariadb://localhost:3306"
  each.propertie.here.is.a.file: | 
    testing=123