apiVersion: v1
kind: Pod

metadata:
  name: web-pod
  labels:
    app-type: web-app-label
spec:
  containers:
    - name: web-server-apache
      image: httpd
      ports:
        - containerPort: 80
