apiVersion: v1
kind: Pod

metadata:
  name: resources-pod
spec:
  containers:
    - name: apache-container
      image: httpd
      resources:
        requests:
          cpu: "500m" # 0.5cpu
          memory: "128Mi"
        limits:
          cpu: "1000m" # 1cpu
          memory: "256Mi"
