apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth  # this prop require use username and password props. There are another kind of types like tls or ssh

data:
  username: YWRtaW4K
  password: UGFzcy0xMjMK
  extra-key: UGFzcy0xMjMK

stringData:
  extra2: "value2"
