apiVersion: v1
kind: Pod
metadata:
  name: pod-apache # 10.244.1.124 the pod IP was got using `kubectl get pods -o wide`
spec:
  containers:
    - name: my-apache-container
      image: httpd
---
apiVersion: v1
kind: Pod
metadata:
  name: my-nginx # 10.244.1.123 `kubectl get pods -o wide`
spec:
  containers:
    - name: my-nginx-container
      image: nginx
