apiVersion: v1
kind: Endpoints

metadata:
  name: my-endpoints-service # this name MUST be the same name of the service
subsets:
  - addresses:
      - ip: 10.244.1.124 # Apache `kubectl get pods -o wide`
      - ip: 10.244.1.123 # Nginx  `kubectl get pods -o wide`
      - ip: 77.68.88.76 # Any external IP on internet
    ports:
      - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-endpoints-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80