apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
  labels:
    app: frontend

spec:
  template:
    metadata:
      name: pod-web-server
      labels:
        apps: my-app
        tier: frontend
    spec:
      containers:
        - name: my-container-nginx
          image: nginx
      nodeSelector: # Using node selector with label disktype: ssd
        disktype: ssd
  selector:
    matchLabels:
      apps: my-app
